#!/usr/bin/env bash
# End-to-end demo: a real STARK proof, generated by the real zkvm-host-server,
# gets paid out on a real (local) chain through contracts/.
#
# This is the thing docs/HOST_SERVICE.md and docs/ONCHAIN_VERIFIER.md both flag
# as missing: the server and contracts/ don't talk to each other yet. This script
# is that wiring, using the honest interim trust model that already exists
# (AttestedVerifier) rather than pretending a trustless on-chain STARK verifier
# is here -- it is not, see docs/ONCHAIN_VERIFIER.md for what that would take.
#
# What this proves, concretely: a task posted with a real ETH reward gets paid
# to the prover automatically by contract logic once (a) a real proof was
# generated by zkvm-host-server, (b) verified locally by `zkvm verify`, and
# (c) attested on-chain by the party that ran that verification -- not before.
#
# Requires: anvil, cast, forge (Foundry), xxd, jq, and a `cargo build --release
# --workspace` already run from the repo root.
set -euo pipefail
cd "$(dirname "$0")/.."

RPC=http://127.0.0.1:8545
SERVER=http://127.0.0.1:4477
PROGRAM=examples/fibonacci_like.zkasm
PROOF_FILE=$(mktemp -t onchain_demo_proof)

# Anvil's well-known, deterministic default accounts. Fine for a local demo;
# never use these keys anywhere real funds could reach them.
ATTESTER_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
DEPLOYER_KEY=$ATTESTER_KEY
ATTESTER_ADDR=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
REQUESTER_KEY=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
PROVER_KEY=0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
PROVER_ADDR=0x90F79bf6EB2c4f870365E785982E1f101E93b906

ANVIL_PID=""
SERVER_PID=""
cleanup() {
  [ -n "$SERVER_PID" ] && kill "$SERVER_PID" 2>/dev/null || true
  [ -n "$ANVIL_PID" ] && kill "$ANVIL_PID" 2>/dev/null || true
  rm -f "$PROOF_FILE"
}
trap cleanup EXIT

echo "=== starting anvil (local chain) ==="
anvil >/tmp/onchain_demo_anvil.log 2>&1 &
ANVIL_PID=$!
for _ in $(seq 1 30); do
  curl -s -X POST -H 'content-type: application/json' \
    --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' "$RPC" >/dev/null 2>&1 && break
  sleep 0.3
done

echo "=== starting zkvm-host-server (the real prover) ==="
./target/release/zkvm-host-server >/tmp/onchain_demo_server.log 2>&1 &
SERVER_PID=$!
for _ in $(seq 1 30); do
  curl -sf "$SERVER/healthz" >/dev/null 2>&1 && break
  sleep 0.3
done

echo "=== deploying contracts ==="
cd contracts
VERIFIER=$(forge create src/AttestedVerifier.sol:AttestedVerifier \
  --rpc-url "$RPC" --private-key "$DEPLOYER_KEY" --broadcast --json \
  --constructor-args "$ATTESTER_ADDR" | jq -r '.deployedTo')
echo "AttestedVerifier: $VERIFIER"

ORCHESTRATOR=$(forge create src/ProofOrchestrator.sol:ProofOrchestrator \
  --rpc-url "$RPC" --private-key "$DEPLOYER_KEY" --broadcast --json \
  --constructor-args "$VERIFIER" | jq -r '.deployedTo')
echo "ProofOrchestrator: $ORCHESTRATOR"
cd ..

echo "=== requester posts a task with a 1 ETH reward ==="
# publicInputsHash is keccak256 of the exact .zkasm program text (see
# contracts/src/IProofVerifier.sol) -- both the requester and the attester
# derive it the same way, from the program alone.
PROGRAM_HEX="0x$(xxd -p "$PROGRAM" | tr -d '\n')"
PUBLIC_INPUTS_HASH=$(cast keccak "$PROGRAM_HEX")
echo "publicInputsHash: $PUBLIC_INPUTS_HASH"

SUBMIT_RECEIPT=$(cast send "$ORCHESTRATOR" "submitTask(bytes32)" "$PUBLIC_INPUTS_HASH" \
  --value 1ether --private-key "$REQUESTER_KEY" --rpc-url "$RPC" --json)
TASK_ID=$(echo "$SUBMIT_RECEIPT" | jq -r '.logs[0].topics[1]')
echo "taskId: $TASK_ID"

echo "=== prover claims the task ==="
cast send "$ORCHESTRATOR" "claimTask(bytes32)" "$TASK_ID" \
  --private-key "$PROVER_KEY" --rpc-url "$RPC" >/dev/null

echo "=== prover asks the real server for a real proof ==="
./target/release/zkvm deploy "$PROGRAM" --server "$SERVER" --out "$PROOF_FILE"

echo "=== prover verifies it locally BEFORE anything touches the chain ==="
./target/release/zkvm verify "$PROGRAM" "$PROOF_FILE"

PROOF_HEX="0x$(xxd -p "$PROOF_FILE" | tr -d '\n')"
PROOF_HASH=$(cast keccak "$PROOF_HEX")

echo "=== attester (the party that just ran zkvm verify) attests on-chain ==="
# This is the trust bridge, not a cryptographic verifier -- see
# docs/ONCHAIN_VERIFIER.md. It only fires because the local verify above
# actually succeeded; never attest to a proof that didn't verify locally.
cast send "$VERIFIER" "attest(bytes32,bytes32)" "$PUBLIC_INPUTS_HASH" "$PROOF_HASH" \
  --private-key "$ATTESTER_KEY" --rpc-url "$RPC" >/dev/null

BALANCE_BEFORE=$(cast balance "$PROVER_ADDR" --rpc-url "$RPC")

echo "=== prover submits the proof and gets paid ==="
cast send "$ORCHESTRATOR" "submitProof(bytes32,bytes)" "$TASK_ID" "$PROOF_HEX" \
  --private-key "$PROVER_KEY" --rpc-url "$RPC" >/dev/null

BALANCE_AFTER=$(cast balance "$PROVER_ADDR" --rpc-url "$RPC")

echo
echo "prover balance before: $BALANCE_BEFORE wei"
echo "prover balance after:  $BALANCE_AFTER wei"
if python3 -c "import sys; sys.exit(0 if int('$BALANCE_AFTER') > int('$BALANCE_BEFORE') else 1)"; then
  echo "OK: a real proof, generated by the real server, was paid out on-chain."
else
  echo "FAILED: balance did not increase -- something in the chain above is broken." >&2
  exit 1
fi
